//POST: Cadastro de um novo produto

POST http://localhost:6070/produto
Content-Type: application/json
Accept: application/json

{
  "id": 50,
  "nome": "MD5",
  "descricao": "vai por favor",
  "fotoUrl": "https://elojobhigh.com.br/assets/img/high-notebook.webp",
  "dataCadastro": "2021-09-26",
  "valorUnitario": "19.90"
}



###
//GET: Busca de produtos por nome e/ou faixa de valor

GET http://localhost:6070/produto?nome=RANQUEADA%20SOLO/DUO&valorMinimo=5.00&valorMaximo=26.00
Accept: application/json


###
//GET:  Visualizar dados do produto

GET http://localhost:6070/produto/2
Accept: application/json